### ISSUE TITLE
Bug and Fix

### ISSUE THREAD

**Issue by SohrabZ** [ktquez/laravel-tinymce#8]
In Laravel 5.2.*
you must change tinymce.php config file from :

`'cdn' => url('vendor/js/tinymce/tinymce.min.js'),`

to:

`'cdn' => Config('app.url').'/vendor/js/tinymce/tinymce.min.js',`

in order to make artisan work again or it will give you this error :

`Catchable fatal error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in  *****\vendor\laravel\framework\src\Illuminate\Routing\RoutingServiceProvider.php on line 62 and defined in *****\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php on line 103`

**Comment by manzwebdesigns** [comment]
I am using Laravel 5.0 and I fixed the same issue by doing this
``
	'cdn' => $app->runningInConsole() ? config('app.url') : url('vendor/js/tinymce/tinymce.min.js'),
``

**Comment by ktquez** [comment]
@manzwebdesigns 
You could take a pull request with these changes?
I would be grateful

**Comment by manzwebdesigns** [comment]
Consider it done!

**Comment by ktquez** [comment]
@manzwebdesigns 
This week I'm overbooked and did not have time to solve this fix, thank you man

**Comment by manzwebdesigns** [comment]
If I find more, I will send them your way.  I am having a little issue using
the output from tinymce when I push it.  I am building an online personal
journal (at http://www.my-journal.us) and am encrypting the entry so it can't
be seen in the database.  

  

I need to encrypt it because I want the users to not worry if someone else can
see their journal information.

  

Thank you for a great bundle!

Bud

On Jun 5 2016, at 7:53 pm, Alan Albuquerque &lt;notifications@github.com&gt;
wrote:  

> [@manzwebdesigns](https://github.com/manzwebdesigns)  
This week I'm overbooked and did not have time to solve this fix, thank you
man

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly, [view it on GitHub](https://github.com/ktquez
/laravel-tinymce/issues/8#issuecomment-223845673), or [mute the thread](https:
//github.com/notifications/unsubscribe/AAzZxm1DloKqITUsqPc3WKCYuYI3NxvLks5qI2G
TgaJpZM4Ip1aZ).![](https://github.com/notifications/beacon/AAzZxgAyQ7W0uBKJT_d
tTdFoJe6fC2wAks5qI2GTgaJpZM4Ip1aZ.gif)

**Comment by ktquez** [comment]
Very good, I can help whenever you want. 
Thanks again and great project, I would like to see when you are ready.

**Comment by manzwebdesigns** [comment]
I actually figured out what the issue was... I had set required on the textarea that was being used for the message.  It is working now. :+1:
